import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent
ICONS_DIR = BASE_DIR / 'resources'  
DEFAULT_DIR = Path.home()
DEFAULT_FILE_PATH = ""
SAVE_FILE = Path(BASE_DIR / "resources" / "last_save" / "last_save.txt")
ENCODING = "cp1251"
COLORS = [
    "black",
    "red",
    "lime",
    "blue",
    "brown",
    "purple",
    "grey",
    "orange",
    "green",
    "c",
    "m",
    "yellow",
    "pink",
    "darkblue",
    "darkred",
]
MARKERS = ["o", "s", "D", "^", "v", "*", "+", "x", ".", '>', '<', 'd', 'p', 'h', 'X']
SIZING = [
    "отн. ед",
    "rel. units",
    "%",
    "Вт",
    "W",
    "МВт",
    "MW",
    "кВт",
    "kW",
    "Па",
    "Pa",
    "МПа",
    "MPa",
    "м",
    "m",
    "мм",
    "mm",
    "°C",
    "кг/с",
    "kg/s",
    "т/ч",
    "t/h",
    "г/кг",
    "g/kg",
    "кг",
    "kg",
    "т",
    "t",
    "кг/м3",
    "kg/m3",
    "Дж",
    "J",
    "Дж/кг",
    "J/kg",
]
UNITS = {
    "МДж": r"\text{МДж}",
    "кДж": r"\text{кДж}",
    "Дж": r"\text{Дж}",
    "MJ": r"\text{MJ}",
    "kJ": r"\text{kJ}",
    "J": r"\text{J}",
    "МВт": r"\text{МВт}",
    "кВт": r"\text{КВт}",
    "Вт": r"\text{Вт}",
    "MW": r"\text{MW}",
    "kW": r"\text{kW}",
    "м": r"\text{м}",
    "мм": r"\text{мм}",
    "m": r"\text{m}",
    "mm": r"\text{mm}",
    "м3": r"\text{м}^3",
    "м2": r"\text{м}^2",
    "m3": r"\text{m}^3",
    "m2": r"\text{m}^2",
    "кг": r"\text{кг}",
    "kg": r"\text{kg}",
    "т": r"\text{т}",
    "t": r"\text{t}",
    "°C": r"\text{°C}",
    "%": r"\text{%}",
    "МПа": r"\text{МПа}",
    "кПа": r"\text{кПа}",
    "MPa": r"\text{MPa}",
    "kPa": r"\text{kPa}",
    "кг/с": r"\frac{\text{кг}}{\text{с}}",
    "т/ч": r"\frac{\text{т}}{\text{ч}}",
    "kg/s": r"\frac{\text{kg}}{\text{s}}",
    "t/h": r"\frac{\text{t}}{\text{h}}",
    "г/кг": r"\frac{\text{г}}{\text{кг}}",
    "g/kg": r"\frac{\text{g}}{\text{kg}}",
    "1/c": r"\frac{\text{1}}{\text{c}}",
    "1/s": r"\frac{\text{1}}{\text{s}}",
    "Дж/г": r"\frac{\text{Дж}}{\text{г}}",
    "Дж/кг": r"\frac{\text{Дж}}{\text{кг}}",
    "J/g": r"\frac{\text{J}}{\text{g}}",
    "J/kg": r"\frac{\text{J}}{\text{kg}}",
    "кг/м3": r"\frac{\text{кг}}{\text{м}^3}",
    "kg/m3": r"\frac{\text{kg}}{\text{m}^3}",
    "отн. ед": r"\text{отн. ед}",
    "rel. units": r"\text{rel. units}",
}
MAIN_CHARS = [
    "N",
    "P",
    "T",
    "H",
    "G",
    "R",
    "Q",
    "C",
    "rho",
    "alpha",
    "beta",
    "tau",
    "gamma",
    "delta",
]
